// get csv data

// format into json

var data = [
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Burma",
    "TotalStateCasesForCountryOfOrigin":"17",
    "DestinationCity":"Birmingham",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Burma",
    "TotalStateCasesForCountryOfOrigin":"17",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"16",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Colombia",
    "TotalStateCasesForCountryOfOrigin":"13",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"13",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Dem. Rep. Congo",
    "TotalStateCasesForCountryOfOrigin":"36",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"36",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Eritrea",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Ethiopia",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Iran",
    "TotalStateCasesForCountryOfOrigin":"6",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"6",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Iraq",
    "TotalStateCasesForCountryOfOrigin":"21",
    "DestinationCity":"Foley",
    "CityCasesforCountryOfOrigin":"3",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Iraq",
    "TotalStateCasesForCountryOfOrigin":"21",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"18",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Ivory Coast",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Somalia",
    "TotalStateCasesForCountryOfOrigin":"8",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"8",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alabama",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"105",
    "CountryOfOrigin":"Sudan",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Mobile",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Bhutan",
    "TotalStateCasesForCountryOfOrigin":"4",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"4",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Burma",
    "TotalStateCasesForCountryOfOrigin":"11",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"11",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Congo",
    "TotalStateCasesForCountryOfOrigin":"3",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"3",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Dem. Rep. Congo",
    "TotalStateCasesForCountryOfOrigin":"23",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"23",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Eritrea",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Ethiopia",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Iraq",
    "TotalStateCasesForCountryOfOrigin":"6",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"6",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Russia",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Fairbanks",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Somalia",
    "TotalStateCasesForCountryOfOrigin":"69",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"69",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Sudan",
    "TotalStateCasesForCountryOfOrigin":"19",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"19",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Ukraine",
    "TotalStateCasesForCountryOfOrigin":"7",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"3",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Ukraine",
    "TotalStateCasesForCountryOfOrigin":"7",
    "DestinationCity":"Wasilla",
    "CityCasesforCountryOfOrigin":"4",
    "TotalNationalCases":"69,933"
  },
  {
    "BeginningDate":"From: 01 Oct 2014",
    "EndDate":"To: 30 Sep 2015",
    "State":"Alaska",
    "FiscalYear":"FY 2015",
    "TotalStateCases":"146",
    "CountryOfOrigin":"Uzbekistan",
    "TotalStateCasesForCountryOfOrigin":"1",
    "DestinationCity":"Anchorage",
    "CityCasesforCountryOfOrigin":"1",
    "TotalNationalCases":"69,933"
  }
];

// for each state, count up total refugee settlement
