var mongoose = require('mongoose');


var data2014Schema = new mongoose.Schema({
  "State" : String,
  "Grand Total" : Number,
  "AFGHANISTAN" : Number,
  "ALGERIA" : Number,
  "ARMENIA" : Number,
  "AZERBAIJAN" : Number,
  "BAHRAIN" : Number,
  "BANGLADESH" : Number,
  "BELARUS" : Number,
  "BHUTAN" : Number,
  "BRAZIL" : Number,
  "BURMA" : Number,
  "BURUNDI" : Number,
  "CAMBODIA" : Number,
  "CAMEROON" : Number,
  "CENTRAL AFRICAN REPUBLIC" : Number,
  "CHAD" : Number,
  "CHINA" : Number,
  "COLOMBIA" : Number,
  "CONGO" : Number,
  "CUBA" : Number,
  "DRC" : Number,
  "DJIBOUTI" : Number,
  "ECUADOR" : Number,
  "EGYPT" : Number,
  "ERITREA" : Number,
  "ETHIOPIA" : Number,
  "GABON" : Number,
  "GEORGIA" : Number,
  "GHANA" : Number,
  "GUINEA" : Number,
  "HAITI" : Number,
  "INDIA" : Number,
  "INDONESIA" : Number,
  "IRAN" : Number,
  "IRAQ" : Number,
  "IVORY COAST" : Number,
  "JORDAN" : Number,
  "KAZAKHSTAN" : Number,
  "KENYA" : Number,
  "KOREA NORTH" : Number,
  "KUWAIT" : Number,
  "KYRGYZSTAN" : Number,
  "LAOS" : Number,
  "LEBANON" : Number,
  "LIBERIA" : Number,
  "LIBYA" : Number,
  "MALI" : Number,
  "MAURITANIA" : Number,
  "MOLDOVA" : Number,
  "MOROCCO" : Number,
  "NEPAL" : Number,
  "NIGERIA" : Number,
  "PAKISTAN" : Number,
  "PALESTINE" : Number,
  "PHILIPPINES" : Number,
  "REPUBLIC OF SOUTH SUDAN" : Number,
  "RUSSIA" : Number,
  "RWANDA" : Number,
  "SAUDI ARABIA" : Number,
  "SIERRA LEONE" : Number,
  "SINGAPORE" : Number,
  "SOMALIA" : Number,
  "SOUTH AFRICA" : Number,
  "SRI LANKA" : Number,
  "SUDAN" : Number,
  "SYRIA" : Number,
  "TANZANIA" : Number,
  "THAILAND" : Number,
  "THE GAMBIA" : Number,
  "TOGO" : Number,
  "TUNISIA" : Number,
  "TURKMENISTAN" : Number,
  "UGANDA" : Number,
  "UKRAINE" : Number,
  "UNKNOWN" : Number,
  "UZBEKISTAN" : Number,
  "VIETNAM" : Number,
  "WEST BANK" : Number,
  "YEMEN" : Number,
  "ZIMBABWE" : Number
});

var data2014 = mongoose.model('data2014', data2014Schema);

module.exports = data2014;
