var mongoose = require('mongoose');


var data2012Schema = new mongoose.Schema({
  "State": String,
  "AFGHANISTAN": Number,
  "ANGOLA": Number,
  "ARMENIA": Number,
  "AUSTRIA": Number,
  "AZERBAIJAN": Number,
  "BELARUS": Number,
  "BENIN": Number,
  "BHUTAN": Number,
  "BOTSWANA": Number,
  "BURMA": Number,
  "BURUNDI": Number,
  "CAMBODIA": Number,
  "CAMEROON": Number,
  "CENTRAL AFRICAN REPUBLIC": Number,
  "CHAD": Number,
  "CHINA": Number,
  "COLOMBIA": Number,
  "CONGO": Number,
  "CUBA": Number,
  "DRC": Number,
  "DJIBOUTI": Number,
  "ECUADOR": Number,
  "EGYPT": Number,
  "ERITREA": Number,
  "ESTONIA": Number,
  "ETHIOPIA": Number,
  "GABON": Number,
  "GAZA STRIP": Number,
  "GEORGIA": Number,
  "GUINEA": Number,
  "INDIA": Number,
  "INDONESIA": Number,
  "IRAN": Number,
  "IRAQ": Number,
  "ISRAEL": Number,
  "IVORY COAST": Number,
  "JORDAN": Number,
  "KAZAKHSTAN": Number,
  "KENYA": Number,
  "KOREA NORTH": Number,
  "KUWAIT": Number,
  "KYRGYZSTAN": Number,
  "LAOS": Number,
  "LEBANON": Number,
  "LIBERIA": Number,
  "LIBYA": Number,
  "MALAYSIA": Number,
  "MALI": Number,
  "MOLDOVA": Number,
  "MOROCCO": Number,
  "MOZAMBIQUE": Number,
  "NEPAL": Number,
  "NIGER": Number,
  "NIGERIA": Number,
  "PAKISTAN": Number,
  "PALESTINE": Number,
  "PHILIPPINES": Number,
  "REPUBLIC OF SOUTH SUDAN": Number,
  "RUSSIA": Number,
  "RWANDA": Number,
  "SAUDI ARABIA": Number,
  "SENEGAL": Number,
  "SIERRA LEONE": Number,
  "SLOVAKIA": Number,
  "SOMALIA": Number,
  "SOUTH AFRICA": Number,
  "SRI LANKA": Number,
  "SUDAN": Number,
  "SYRIA": Number,
  "TAJIKISTAN": Number,
  "TANZANIA": Number,
  "THAILAND": Number,
  "THE GAMBIA": Number,
  "TOGO": Number,
  "TUNISIA": Number,
  "TURKEY": Number,
  "UGANDA": Number,
  "UKRAINE": Number,
  "UNITED ARAB EMIRATES": Number,
  "UZBEKISTAN": Number,
  "VENEZUELA": Number,
  "VIETNAM": Number,
  "WEST BANK": Number,
  "ZAMBIA": Number,
  "ZIMBABWE": Number,
  "Grand Total": Number
});

var data2012 = mongoose.model('data2012', data2012Schema);

module.exports = data2012;
